name: example
on:
  workflow_call:
    inputs:
      env_name:
      required: true
      type: string
  
  outputs:
      environment:
        description: "The passed environment"
        value: ${{ jobs.process-env.outputs.environment }}

jobs:
  process-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.env }}
    steps:
      - name: Set environment variable
        id: set-env
        run: echo "env=${{ inputs.env_name }}" >> $GITHUB_OUTPUT

        
  

