name: Print Inputs Example

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Your GitHub username'
        required: true
        default: 'guest'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
      name:
        type: choice
        description: choose a name
        options:
         - vaishnavi
         - good girl
          

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Username: ${{ github.event.inputs.username }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "name: ${{github.event.inputs.name}}"

