name: Pass Inputs Between Jobs

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Enter environment name'
        required: true
        default: 'dev'

jobs:
  job-a:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.env }}
    steps:
      - name: Set environment name from input
        id: set-env
        run: |
          echo "env=${{ github.event.inputs.env_name }}" >> $GITHUB_OUTPUT

  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - name: Use environment value
        run: echo "Deploying to ${{ needs.job-a.outputs.environment }}"
