name: Main Workflow Using workflow_call

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Enter environment name'
        required: true
        default: 'dev'

jobs:
  call-reusable:
    uses: ./.github/workflows/blank.yml
    with:
      env_name: ${{ github.event.inputs.env_name }}
    secrets: inherit  # If your reusable workflow needs secrets

  deploy:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - name: Use the environment output
        run: echo "Deploying to ${{ needs.call-reusable.outputs.environment }}"
